### PR TITLE
Increased logging in master sync.

### PR DESCRIPTION
**Pull request by deng02**
Added more logging around synchronization to help with tracking changes in the local ROS master due to multimaster.  Also added which masters are returned by master discovery and split out the horrible hack message to help with readability (was very dense for when there are alot of publishers in the list).

### CODE REVIEW

**Comment by atiderko** [comment]
Hi deng02,

thank you for improving and this pull request.
Unfortunately, this leads to this error (to unsubscribe we need no topictype):
`[ERROR] [WallTime: 1478760398.801523] SyncThread[tiderko_11312] ERROR: Traceback (most recent call last):
  File "/ros/src/multimaster_fkie/master_sync_fkie/src/master_sync_fkie/sync_thread.py", line 308, in _apply_remote_state
    self.name, node, nodeuri, topic, topictype)
UnboundLocalError: local variable 'topictype' referenced before assignment
`
I think, it will be the same at line 339.

Can you fix this, please?

**Comment by deng02** [comment]
Updated PR with the variable removed. Thanks for the catch!

**Comment by deng02** [comment]
Hi atiderko,

I was wondering if it was possible to have this merged in? Or are there any other concerns? I'd be happy to address any issues.   

Denise

**Comment by atiderko** [comment]
Hi deng02,

thank you for contributing!

It was possible to merge into the branch because there are no (unit/ros)tests defined to find a runtime error.   Someone should create one ;-). So github checks only for conflicts in the code.

Alex

**Comment by deng02** [comment]
Thanks so much for the merge!  The failure was totally my fault, I should have written a unit test to more properly test my change :) and submitted it.  I will do that next itme.

**Pull request merged**
